### PR TITLE
Additional functionality for plot saving

### PR DESCRIPTION
**Pull request by ninadicara**
While I was creating the plots in the other PR I had thoughts about some small enhancements which are discussed here. 

Changes:
- In `core.py` are two new methods for managing writing out plots. These are `write_plots`, which calls `unique_filename`. 
- Two new examples files in the Examples folder.

New functionality: 
- If user requested 'write_directory' does not exist (e.g. defined a new subfolder like `/plots`) then the function will create this directory and write the file there. 
- If the default filename is already in use it will append a number to the end of the filename so as not to overwrite existing plots. 
- Two new args are also introduced in savefig, `bbox=tight` makes sure the whole plot is in the saved figure, and `dpi` has been set to 300 for high quality images.
- Creation of the file path for writing out has been changed to use the `os` package which manages some typical filepath issues (e.g. trailing slashes) and is a bit more stable that string concatenation. 

Notes:
I'd suggest checking this out and testing it on your local Windows machine before merging, just to check it works with the Windows user-defined file paths too (such as the one in the original examples file).

I've implemented this as a method which is called as the file writes out, instead of generating the unique file name through a setter type method in the constructor - I didn't want to mess with what is already written - but it could do this if desired. Same with the write_directory.

### CODE REVIEW

**Comment by ninadicara** [comment]
Also, just to say that if either of these is not desired functionality then of course no need to merge it in! Got a bit carried away last night 😄

**Comment by sbaker-dev** [comment]
RE- Unique_filename: This is great, and absolutely needs to be in the release version, when i was testing it i was unconcerned about it overwriting but that isn't desirable functionality..

RE-write_plot: Makes sense, although given this library will be extended to other python / potentially R input i think the args of a sea-born objected might lead to problems later. It doesn't matter right now, just something we need to keep in mind. 

I appreciated you not wanting to overwrite stuff but that's perfectly OK. I agree with the principle that the name should be in the constructor. At the moment self._figure names takes a user arg and is only use is to be called in write_plot . So i think it makes more sense to set file_path in the constructor , potentially via a method, so that self._figure name becomes self._file_path or something like that. 

RE-os: That's great, managing for different separators was on a list of things to do so that will help.

RE-examples: I tested them examples and they work. Setting a directory to where the code from is cool, although personally i would want my Plot's graphs in the project directory of the paper/whatever i'm working on rather than my IDE/coding directory.  Nothing wrong with including it, just a comment on use case i guess. 

If you can change the file_path to be constructor, however you see fit, then i will merge this through.

**Comment by ninadicara** [comment]
Hi @sbaker-dev - updated a little so that the docstrings are more consistent with yours, and the file_path is set in the constructor :)

**Comment by sbaker-dev** [comment]
Thanks @ninadicara 

Something i didn't notice until having to review code for public release is that , even though have been used reST for nearly a year is that it doesn't default to :key when keywords are used.... So many of my docstings will need updating but i will handle that. If you are willing to use reST however, that would be great as it keeps a consistent style.

I have a deadline Monday Night but i will be able to do another major commit before the meeting on Wednesday. 

Thanks for your work as always

**Pull request merged**
